var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Ez a videó a(z) „##DEVICE_NAME##” eszközön játszódik.',

    '##TVOUT_DEVICE_TYPE##': 'Tv csatlakoztatva',
    '##TVOUT_DEVICE_NAME##': 'Ez a videó a TV-készüléken van lejátszva.',

    'Aborted': 'Megszakítva',
    'Audio Playback': 'Hanglejátszás',
    'Captions': 'Szöveges átiratok',
    'Choose Wireless Display': 'Vezeték nélküli kijelző kiválasztása',
    'Display Full Screen': 'Teljesképernyős megjelenítés',
    'Duration': 'Időtartam',
    'Elapsed': 'Eltelt',
    'Error': 'Hiba',
    'Exit Full Screen': 'Kilépés a teljes képernyőről',
    'Fast Forward': 'Előretekerés',
    'Live Broadcast': 'Élő adás',
    'Loading': 'Betöltés',
    'Maximum Volume': 'Maximális hangerő',
    'Minimum Volume': 'Minimális hangerő',
    'Mute': 'Némítás',
    'Pause': 'Szüneteltetés',
    'Play': 'Lejátszás',
    'Remaining': 'Hátralévő',
    'Rewind': 'Visszatekerés',
    'Rewind ##sec## Seconds': '##sec## másodperc visszatekerése',
    'Stalled': 'Leállt',
    'Start Playback': 'Lejátszás megkezdése',
    'Subtitles': 'Feliratok',
    'Suspended': 'Felfüggesztve',
    'Unmute': 'Némítás megszüntetése',
    'Video Playback': 'Videolejátszás',
    'Volume': 'Hangerő',
    'Waiting': 'Várakozás'
};