var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Deze video wordt afgespeeld op \'##DEVICE_NAME##\'.',

    '##TVOUT_DEVICE_TYPE##': 'Verbonden met tv',
    '##TVOUT_DEVICE_NAME##': 'Deze video wordt afgespeeld op de tv.',

    'Aborted': 'Afgebroken',
    'Audio Playback': 'Audio afspelen',
    'Captions': 'Ondertiteling',
    'Choose Wireless Display': 'Kies draadloos scherm',
    'Display Full Screen': 'Schermvullende weergave',
    'Duration': 'Duur',
    'Elapsed': 'Verstreken',
    'Error': 'Fout',
    'Exit Full Screen': 'Schakel schermvullende weergave uit',
    'Fast Forward': 'Spoel vooruit',
    'Live Broadcast': 'Live-uitzending',
    'Loading': 'Laden',
    'Maximum Volume': 'Maximaal volume',
    'Minimum Volume': 'Minimaal volume',
    'Mute': 'Uit',
    'Pause': 'Pauze',
    'Play': 'Speel af',
    'Remaining': 'Resterend',
    'Rewind': 'Spoel terug',
    'Rewind ##sec## Seconds': 'Spoel ##sec## seconden terug',
    'Stalled': 'Gestopt',
    'Start Playback': 'Start afspelen',
    'Subtitles': 'Ondertiteling',
    'Suspended': 'Onderbroken',
    'Unmute': 'Geluid aan',
    'Video Playback': 'Video afspelen',
    'Volume': 'Volume',
    'Waiting': 'Wachten'
};