var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Το βίντεο αυτό αναπαράγεται στο «##DEVICE_NAME##».',

    '##TVOUT_DEVICE_TYPE##': 'Τηλεόραση συνδεδεμένη',
    '##TVOUT_DEVICE_NAME##': 'Αυτό το βίντεο αναπαράγεται στην τηλεόραση.',

    'Aborted': 'Ματαιώθηκε',
    'Audio Playback': 'Αναπαραγωγή ήχου',
    'Captions': 'Λεζάντες',
    'Choose Wireless Display': 'Επιλογή ασύρματης οθόνης',
    'Display Full Screen': 'Εμφάνιση σε πλήρη οθόνη',
    'Duration': 'Διάρκεια',
    'Elapsed': 'Παρήλθε',
    'Error': 'Σφάλμα',
    'Exit Full Screen': 'Έξοδος από πλήρη οθόνη',
    'Fast Forward': 'Γρήγορη κίνηση προς τα μπροστά',
    'Live Broadcast': 'Ζωντανή μετάδοση',
    'Loading': 'Φόρτωση',
    'Maximum Volume': 'Μέγιστη ένταση ήχου',
    'Minimum Volume': 'Ελάχιστη ένταση ήχου',
    'Mute': 'Σίγαση',
    'Pause': 'Παύση',
    'Play': 'Αναπαραγωγή',
    'Remaining': 'Απομένουν',
    'Rewind': 'Γρήγορη επαναφορά',
    'Rewind ##sec## Seconds': 'Γρήγορη επαναφορά κατά ##δ.## δευτερόλεπτα',
    'Stalled': 'Καθυστέρηση',
    'Start Playback': 'Έναρξη αναπαραγωγής',
    'Subtitles': 'Υπότιτλοι',
    'Suspended': 'Σε αναστολή',
    'Unmute': 'Κατάργηση σίγασης',
    'Video Playback': 'Αναπαραγωγή βίντεο',
    'Volume': 'Ένταση ήχου',
    'Waiting': 'Σε αναμονή'
};