var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': '正在“##DEVICE_NAME##”上播放此视频。',

    '##TVOUT_DEVICE_TYPE##': '电视机已连接',
    '##TVOUT_DEVICE_NAME##': '正在电视上播放此视频。',

    'Aborted': '已中止',
    'Audio Playback': '音频回放',
    'Captions': '字幕',
    'Choose Wireless Display': '选取无线显示器',
    'Display Full Screen': '以全屏幕显示',
    'Duration': '时间长度',
    'Elapsed': '经过',
    'Error': '错误',
    'Exit Full Screen': '退出全屏幕',
    'Fast Forward': '快进',
    'Live Broadcast': '实时广播',
    'Loading': '正在载入',
    'Maximum Volume': '最大音量',
    'Minimum Volume': '最小音量',
    'Mute': '静音',
    'Pause': '暂停',
    'Play': '播放',
    'Remaining': '剩余',
    'Rewind': '倒回',
    'Rewind ##sec## Seconds': '倒回 ##sec## 秒钟',
    'Stalled': '已停顿',
    'Start Playback': '开始回放',
    'Subtitles': '字幕',
    'Suspended': '已暂停',
    'Unmute': '取消静音',
    'Video Playback': '视频回放',
    'Volume': '音量',
    'Waiting': '正在等待'
};