var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'วิดีโอนี้กำลังเล่นอยู่บน “##DEVICE_NAME##”',

    '##TVOUT_DEVICE_TYPE##': 'ทีวีต่ออยู่',
    '##TVOUT_DEVICE_NAME##': 'วิดีโอนี้กำลังเล่นอยู่บนทีวี',

    'Aborted': 'ล้มเลิก',
    'Audio Playback': 'การเล่นเสียง',
    'Captions': 'คำบรรยายภาพ',
    'Choose Wireless Display': 'เลือกจอแสดงผลไร้สาย',
    'Display Full Screen': 'แสดงเต็มหน้าจอ',
    'Duration': 'ระยะเวลา',
    'Elapsed': 'ผ่านไป',
    'Error': 'ข้อผิดพลาด',
    'Exit Full Screen': 'ออกจากภาพเต็มหน้าจอ',
    'Fast Forward': 'เลื่อนไปข้างหน้าอย่างเร็ว',
    'Live Broadcast': 'ถ่ายทอดสด',
    'Loading': 'กำลังโหลด',
    'Maximum Volume': 'ความดังเสียงสูงสุด',
    'Minimum Volume': 'ความดังเสียงต่ำสุด',
    'Mute': 'ปิดเสียง',
    'Pause': 'พัก',
    'Play': 'เล่น',
    'Remaining': 'เหลืออยู่',
    'Rewind': 'เลื่อนถอยกลับ',
    'Rewind ##sec## Seconds': 'เลื่อนถอยกลับ ##sec## วินาที',
    'Stalled': 'หยุดลง',
    'Start Playback': 'เริ่มเล่น',
    'Subtitles': 'คำบรรยาย',
    'Suspended': 'ระงับอยู่',
    'Unmute': 'เลิกปิดเสียง',
    'Video Playback': 'การเล่นวิดีโอ',
    'Volume': 'ความดัง',
    'Waiting': 'กำลังรอ'
};