var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Este video se está reproduciendo en “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'Televisión conectada',
    '##TVOUT_DEVICE_NAME##': 'Este video se está reproduciendo en la televisión.',

    'Aborted': 'Interrumpido',
    'Audio Playback': 'Reproducción de audio',
    'Captions': 'Subtítulos opcionales',
    'Choose Wireless Display': 'Elegir pantalla inalámbrica',
    'Display Full Screen': 'Pantalla completa',
    'Duration': 'Duración',
    'Elapsed': 'Transcurrido',
    'Error': 'Error',
    'Exit Full Screen': 'Salir de pantalla completa',
    'Fast Forward': 'Avance rápido',
    'Live Broadcast': 'Emisión en vivo',
    'Loading': 'Cargando',
    'Maximum Volume': 'Volumen máximo',
    'Minimum Volume': 'Volumen mínimo',
    'Mute': 'Silenciar',
    'Pause': 'Pausa',
    'Play': 'Reproducir',
    'Remaining': 'Restante',
    'Rewind': 'Retroceder',
    'Rewind ##sec## Seconds': 'Rebobinar ##sec## segundos',
    'Stalled': 'Parado',
    'Start Playback': 'Iniciar reproducción',
    'Subtitles': 'Subtítulos',
    'Suspended': 'Suspendido',
    'Unmute': 'Activar sonido',
    'Video Playback': 'Reproducción de video',
    'Volume': 'Volumen',
    'Waiting': 'Esperando'
};