var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Video ini sedang bermain di “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV Disambung',
    '##TVOUT_DEVICE_NAME##': 'Video ini sedang bermain di TV.',

    'Aborted': 'Dihenti paksa',
    'Audio Playback': 'Main Balik Audio',
    'Captions': 'Kapsyen',
    'Choose Wireless Display': 'Pilih Paparan Wayarles',
    'Display Full Screen': 'Paparkan Skrin Penuh',
    'Duration': 'Tempoh',
    'Elapsed': 'Berlalu',
    'Error': 'Ralat',
    'Exit Full Screen': 'Keluar dari Skrin Penuh',
    'Fast Forward': 'Maju Pantas',
    'Live Broadcast': 'Siaran Langsung',
    'Loading': 'Memuatkan',
    'Maximum Volume': 'Kelantangan Maksimum',
    'Minimum Volume': 'Kelantangan Minimum',
    'Mute': 'Senyap',
    'Pause': 'Jeda',
    'Play': 'Main',
    'Remaining': 'Tinggal',
    'Rewind': 'Putar Balik',
    'Rewind ##sec## Seconds': 'Putar Balik ##saat## Saat',
    'Stalled': 'Tergantung',
    'Start Playback': 'Mulakan Main Semula',
    'Subtitles': 'Sari Kata',
    'Suspended': 'Digantung',
    'Unmute': 'Nyahsenyap',
    'Video Playback': 'Main Balik Video',
    'Volume': 'Kelantangan',
    'Waiting': 'Sedang tunggu'
};