var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'הסרט מוקרן כעת ב״##DEVICE_NAME##״.',

    '##TVOUT_DEVICE_TYPE##': 'טלויזיה מחוברת',
    '##TVOUT_DEVICE_NAME##': 'וידאו זה מוקרן כעת דרף הטלוויזיה.',

    'Aborted': 'בוטל',
    'Audio Playback': 'הפעלת שמע',
    'Captions': 'כתוביות',
    'Choose Wireless Display': 'בחר/י צג אלחוטי',
    'Display Full Screen': 'הצג במסך מלא',
    'Duration': 'אורך',
    'Elapsed': 'זמן שחלף',
    'Error': 'שגיאה',
    'Exit Full Screen': 'צא ממסך מלא',
    'Fast Forward': 'הרץ קדימה',
    'Live Broadcast': 'שידור חי',
    'Loading': 'טוען',
    'Maximum Volume': 'עוצמה מירבית',
    'Minimum Volume': 'עוצמה מזערית',
    'Mute': 'השתק',
    'Pause': 'השהה',
    'Play': 'נגן',
    'Remaining': 'נותרו',
    'Rewind': 'הרץ אחורה',
    'Rewind ##sec## Seconds': 'הרץ ##sec## שניות אחורה',
    'Stalled': 'תקוע',
    'Start Playback': 'הפעל',
    'Subtitles': 'כתוביות',
    'Suspended': 'מושהה',
    'Unmute': 'בטל השתקה',
    'Video Playback': 'הפעלת וידיאו',
    'Volume': 'עוצמת שמע',
    'Waiting': 'ממתין'
};