var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Toto video sa prehráva na „##DEVICE_NAME##“.',

    '##TVOUT_DEVICE_TYPE##': 'TV pripojené',
    '##TVOUT_DEVICE_NAME##': 'Toto video sa prehráva na TV.',

    'Aborted': 'Prerušené',
    'Audio Playback': 'Prehrávanie audia',
    'Captions': 'Skryté titulky',
    'Choose Wireless Display': 'Vybrať bezdrôtový displej',
    'Display Full Screen': 'Zobraziť na celej obrazovke',
    'Duration': 'Trvanie',
    'Elapsed': 'Uplynuté',
    'Error': 'Chyba',
    'Exit Full Screen': 'Vypnúť zobrazenie na celej obrazovke',
    'Fast Forward': 'Rýchle prevíjanie dopredu',
    'Live Broadcast': 'Živé vysielanie',
    'Loading': 'Načítava sa',
    'Maximum Volume': 'Maximálna hlasitosť',
    'Minimum Volume': 'Minimálna hlasitosť',
    'Mute': 'Stíšiť',
    'Pause': 'Pozastaviť',
    'Play': 'Prehrať',
    'Remaining': 'Zostáva',
    'Rewind': 'Prevíjanie dozadu',
    'Rewind ##sec## Seconds': 'Previnúť ##sec## s',
    'Stalled': 'Prerušené',
    'Start Playback': 'Spustiť prehrávanie',
    'Subtitles': 'Titulky',
    'Suspended': 'Zastavené',
    'Unmute': 'Zapnúť zvuk',
    'Video Playback': 'Prehrávanie videa',
    'Volume': 'Hlasitosť',
    'Waiting': 'Čaká sa'
};