var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Denne videoen vises på «##DEVICE_NAME##».',

    '##TVOUT_DEVICE_TYPE##': 'TV tilkoblet',
    '##TVOUT_DEVICE_NAME##': 'Denne videoen vises på TV-en.',

    'Aborted': 'Avbrutt',
    'Audio Playback': 'Lydavspilling',
    'Captions': 'Teksting',
    'Choose Wireless Display': 'Velg trådløs skjerm',
    'Display Full Screen': 'Vis i fullskjermmodus',
    'Duration': 'Varighet',
    'Elapsed': 'Tid brukt',
    'Error': 'Feil',
    'Exit Full Screen': 'Avslutt fullskjermmodus',
    'Fast Forward': 'Spol framover',
    'Live Broadcast': 'Direktesending',
    'Loading': 'Laster inn',
    'Maximum Volume': 'Høyeste volumnivå',
    'Minimum Volume': 'Laveste volumnivå',
    'Mute': 'Lyd av',
    'Pause': 'Pause',
    'Play': 'Spill',
    'Remaining': 'Gjenstår',
    'Rewind': 'Spol tilbake',
    'Rewind ##sec## Seconds': 'Spol tilbake ##sec## sekunder',
    'Stalled': 'Stoppet',
    'Start Playback': 'Start avspilling',
    'Subtitles': 'Undertekster',
    'Suspended': 'Utsatt',
    'Unmute': 'Slå på lyd',
    'Video Playback': 'Videoavspilling',
    'Volume': 'Volum',
    'Waiting': 'Venter'
};