var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Cette vidéo est visionnée sur « ##DEVICE_NAME## ».',

    '##TVOUT_DEVICE_TYPE##': 'Téléviseur connecté',
    '##TVOUT_DEVICE_NAME##': 'Cette vidéo est visionnée sur le téléviseur.',

    'Aborted': 'Interrompu',
    'Audio Playback': 'Lecture audio',
    'Captions': 'Sous-titres',
    'Choose Wireless Display': 'Choisir un moniteur sans fil',
    'Display Full Screen': 'Afficher en mode plein écran',
    'Duration': 'Durée',
    'Elapsed': 'Écoulé',
    'Error': 'Erreur',
    'Exit Full Screen': 'Quitter le mode plein écran',
    'Fast Forward': 'Avance rapide',
    'Live Broadcast': 'Diffusion en direct',
    'Loading': 'Chargement',
    'Maximum Volume': 'Volume maximum',
    'Minimum Volume': 'Volume minimal',
    'Mute': 'Silence',
    'Pause': 'Pause',
    'Play': 'Lire',
    'Remaining': 'Restant',
    'Rewind': 'Rembobiner',
    'Rewind ##sec## Seconds': 'Rembobiner ##sec## secondes',
    'Stalled': 'À l’arrêt',
    'Start Playback': 'Lancer la lecture',
    'Subtitles': 'Sous-titres',
    'Suspended': 'Suspendu',
    'Unmute': 'Activer le son',
    'Video Playback': 'Lecture vidéo',
    'Volume': 'Volume',
    'Waiting': 'En attente'
};