var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Dieses Video wird auf „##DEVICE_NAME##”“ wiedergegeben.',

    '##TVOUT_DEVICE_TYPE##': 'TV angeschlossen',
    '##TVOUT_DEVICE_NAME##': 'Dieses Video wird auf dem TV wiedergegeben.',

    'Aborted': 'Abgebrochen',
    'Audio Playback': 'Audiowiedergabe',
    'Captions': 'Untertitel',
    'Choose Wireless Display': 'Drahtlosen Monitor wählen',
    'Display Full Screen': 'Auf gesamtem Bildschirm anzeigen',
    'Duration': 'Dauer',
    'Elapsed': 'Verstrichen',
    'Error': 'Fehler',
    'Exit Full Screen': 'Vollbild aus',
    'Fast Forward': 'Schneller Vorlauf',
    'Live Broadcast': 'Liveübertragung',
    'Loading': 'Laden',
    'Maximum Volume': 'Maximal-Volume',
    'Minimum Volume': 'Minimale Lautstärke',
    'Mute': 'Stumm',
    'Pause': 'Pause',
    'Play': 'Wiedergeben',
    'Remaining': 'Übrig',
    'Rewind': 'Schneller Rücklauf',
    'Rewind ##sec## Seconds': '#sec## Sekunden zurück',
    'Stalled': 'Keine Antwort',
    'Start Playback': 'Wiedergabe starten',
    'Subtitles': 'Untertitel',
    'Suspended': 'Angehalten',
    'Unmute': 'Ton an',
    'Video Playback': 'Videowiedergabe',
    'Volume': 'Lautstärke',
    'Waiting': 'Warten'
};