var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Це відео відтворюється на «##DEVICE_NAME##».',

    '##TVOUT_DEVICE_TYPE##': 'ТВ підключено',
    '##TVOUT_DEVICE_NAME##': 'Це відео відтворюється на телевізорі.',

    'Aborted': 'Перервано',
    'Audio Playback': 'Відтворення звуку',
    'Captions': 'Супровідний текст',
    'Choose Wireless Display': 'Виберіть бездротовий дисплей',
    'Display Full Screen': 'На весь екран',
    'Duration': 'Тривалість',
    'Elapsed': 'Минуло',
    'Error': 'Помилка',
    'Exit Full Screen': 'Вийти з повноекранного режиму',
    'Fast Forward': 'Перемотування вперед',
    'Live Broadcast': 'Прямий ефір',
    'Loading': 'Відкриваю',
    'Maximum Volume': 'Максимальна гучність',
    'Minimum Volume': 'Мінімальна гучність',
    'Mute': 'Вимкнення звуку',
    'Pause': 'Призупинити',
    'Play': 'Відтворити',
    'Remaining': 'Лишилося',
    'Rewind': 'Перемотати назад',
    'Rewind ##sec## Seconds': 'Назад на ##sec## секунд',
    'Stalled': 'Зупинилося',
    'Start Playback': 'Почати відтворення',
    'Subtitles': 'Субтитри',
    'Suspended': 'Відкладено',
    'Unmute': 'Увімкнути звук',
    'Video Playback': 'Відтворення відео',
    'Volume': 'Гучність',
    'Waiting': 'Чекаю'
};