var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': '此視訊正在「##DEVICE_NAME##」上播放。',

    '##TVOUT_DEVICE_TYPE##': '已連接電視',
    '##TVOUT_DEVICE_NAME##': '此視訊正在電視上播放。',

    'Aborted': '已中止',
    'Audio Playback': '音訊播放',
    'Captions': '字幕',
    'Choose Wireless Display': '選擇無線顯示器',
    'Display Full Screen': '顯示全螢幕',
    'Duration': '播放時間',
    'Elapsed': '已經過',
    'Error': '錯誤',
    'Exit Full Screen': '離開全螢幕',
    'Fast Forward': '快轉',
    'Live Broadcast': '現場直播',
    'Loading': '正在載入',
    'Maximum Volume': '最高音量',
    'Minimum Volume': '最低音量',
    'Mute': '靜音',
    'Pause': '暫停',
    'Play': '播放',
    'Remaining': '剩餘',
    'Rewind': '倒轉',
    'Rewind ##sec## Seconds': '倒轉 ##sec## 秒',
    'Stalled': '已停止',
    'Start Playback': '開始播放',
    'Subtitles': '字幕',
    'Suspended': '已中止',
    'Unmute': '解除靜音',
    'Video Playback': '視訊播放',
    'Volume': '音量',
    'Waiting': '等待中'
};