var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Acest clip video este în redare pe “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV conectat',
    '##TVOUT_DEVICE_NAME##': 'Acest clip video este în redare pe TV.',

    'Aborted': 'Abandonat',
    'Audio Playback': 'Redare audio',
    'Captions': 'Subtitrări',
    'Choose Wireless Display': 'Alege afișajul wireless',
    'Display Full Screen': 'Afișează pe tot ecranul',
    'Duration': 'Durată',
    'Elapsed': 'Timp scurs',
    'Error': 'Eroare',
    'Exit Full Screen': 'Nu mai afișa pe tot ecranul',
    'Fast Forward': 'Repede înainte',
    'Live Broadcast': 'Difuzare live',
    'Loading': 'Încărcare',
    'Maximum Volume': 'Volum maxim',
    'Minimum Volume': 'Volum mimim',
    'Mute': 'Taie sonorul',
    'Pause': 'Suspendă',
    'Play': 'Redă',
    'Remaining': 'Rămas',
    'Rewind': 'Derulare înapoi',
    'Rewind ##sec## Seconds': 'Derulare înapoi ##sec## secunde',
    'Stalled': 'Blocată',
    'Start Playback': 'Pornește redarea',
    'Subtitles': 'Subtitrări',
    'Suspended': 'Suspendată',
    'Unmute': 'Restabilește sonorul',
    'Video Playback': 'Redare video',
    'Volume': 'Volum',
    'Waiting': 'În așteptare'
};