var UIStringTable = {
    '##WIRELESS_PLAYBACK_DEVICE_TYPE##': 'AirPlay',
    '##WIRELESS_PLAYBACK_DEVICE_NAME##': 'Este vídeo está sendo reproduzido em “##DEVICE_NAME##”.',

    '##TVOUT_DEVICE_TYPE##': 'TV Conectada',
    '##TVOUT_DEVICE_NAME##': 'Este vídeo está sendo reproduzido na TV.',

    'Aborted': 'Cancelado',
    'Audio Playback': 'Reprodução de Áudio',
    'Captions': 'Legendas',
    'Choose Wireless Display': 'Escolher Tela sem Fio',
    'Display Full Screen': 'Exibir Tela Cheia',
    'Duration': 'Duração',
    'Elapsed': 'Decorrido',
    'Error': 'Erro',
    'Exit Full Screen': 'Sair da Tela Cheia',
    'Fast Forward': 'Avançar Rapidamente',
    'Live Broadcast': 'Transmissão ao Vivo',
    'Loading': 'Carregando',
    'Maximum Volume': 'Volume Máximo',
    'Minimum Volume': 'Volume Mínimo',
    'Mute': 'Mudo',
    'Pause': 'Pausa',
    'Play': 'Reproduzir',
    'Remaining': 'Restante',
    'Rewind': 'Retroceder',
    'Rewind ##sec## Seconds': 'Retroceder ##sec## Segundos',
    'Stalled': 'Parado',
    'Start Playback': 'Iniciar Reprodução',
    'Subtitles': 'Legendas',
    'Suspended': 'Suspensa',
    'Unmute': 'Reativar Som',
    'Video Playback': 'Reprodução de Vídeo',
    'Volume': 'Volume',
    'Waiting': 'Aguardando'
};